"use client"

import Image from "next/image"
import isLoadingProps from "@/types/isLoading"
import { ChartColumnBig } from "lucide-react"
import { useUnits } from "@/context/provider/UnitsProvider";
import { formatTemp } from "@/lib/unitsConversion";
import { UnitsContextType } from "@/types/unitsProvider";


export default function DailyForecast({ loading, weatherData }: isLoadingProps) {
  const forecast = weatherData?.dailyForecast ?? [];
  const {units}: UnitsContextType = useUnits();
  console.log(units)
  const weeklySummary = forecast.length > 0 
    ? forecast[0].description 
    : "Checking the latest atmospheric conditions for this week.";

  return (
    <div className="w-full flex flex-col space-y-4">
      <h2 className="text-lg font-bold text-left text-foreground">Daily Forecast</h2>

      {/* Dynamic Summary Banner */}
      <div className="flex items-center gap-3 border-border/60 border bg-foreground/2 rounded-xl p-3 max-w-2xl w-full">
        <ChartColumnBig className="w-5 h-5 text-primary shrink-0" />
        <p className="text-sm font-medium tracking-tight text-foreground/80 leading-snug">
          {weeklySummary}
        </p>
      </div>

      {/* Horizontal Viewport Container */}
      <div className="w-full overflow-x-auto custom-scrollbar pb-2">
        <div className="grid grid-flow-col auto-cols-[minmax(85px,1fr)] lg:grid-cols-7 gap-3 min-w-162 lg:min-w-0">
          
          {loading ? (
            // Loading Skeletons
            Array.from({ length: 7 }).map((_, i) => (
              <div
                key={i}
                className="bg-surface rounded-xl p-3 border border-border text-center animate-pulse space-y-3"
              >
                <div className="h-4 w-8 mx-auto bg-foreground/10 rounded" />
                <div className="h-10 w-10 mx-auto bg-foreground/10 rounded-full" />
                <div className="flex justify-between items-center pt-1">
                  <div className="h-3 w-4 bg-foreground/10 rounded" />
                  <div className="h-3 w-4 bg-foreground/10 rounded" />
                </div>
              </div>
            ))
          ) : forecast.length === 0 ? (
            <div className="col-span-full py-6 text-center text-sm text-muted-foreground border border-border/40 rounded-xl">
              Forecast data is currently unavailable.
            </div>
          ) : (
            forecast.map((fc: typeof forecast[number], i: number) => {
              const shortDay = fc.day === "Today" ? "Tdy" : fc.day.substring(0, 3);
              const displayMax = formatTemp(fc.tempMax, units.temperature);
              const displayMin = formatTemp(fc.tempMin, units.temperature);

              return (
                <div
                  key={`${fc.date}-${i}`}
                  className="bg-surface border border-border rounded-xl p-3 text-center hover:bg-foreground/2 transition-colors duration-200 flex flex-col justify-between group cursor-default"
                  title={fc.condition} // Native tooltip on hover for extra context
                >
                  <p className="font-semibold text-xs text-muted-foreground uppercase tracking-wider">
                    {shortDay}
                  </p>
                  
                  {/* Read the absolute URL generated by the API */}
                  <Image
                    src={fc.icon}
                    width={40}
                    height={40}
                    alt={`${fc.day} forecast icon`}
                    className="mx-auto my-2 object-contain drop-shadow-sm filter brightness-105 group-hover:scale-105 transition-transform duration-300"
                    priority={i < 4} // Only prioritize the first few images
                  />
                  
                  <div className="flex justify-between text-xs pt-1 border-t border-border/40 font-medium">
                    <span className="text-foreground font-bold">{displayMax}°</span>
                    <span className="text-muted-foreground/60">{displayMin}°</span>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </div>
    </div>
  )
}